PUT  http://localhost:8080/api/livres/11
Content-Type: application/json

{
    "titre" : "L'Illiade (Edition révisée)",
    "auteur": "Homère",
    "genre" : "Epopée",
    "anneePublication": -800,
    "disponible": false
}